/*
 created by aditya on 17-02-2017
 */

"use strict";

const ActionConstants = {
    TOGGLE_LOGIN_STATUS: "TOGGLE_LOGIN_STATUS",
    TOGGLE_LOADER: "TOGGLE_LOADER",
    GET_SELECTED_COURSE: "GET_SELECTED_COURSE",
    UPDATE_SELECTED_COURSE: "UPDATE_SELECTED_COURSE",
    TOGGLE_NAVIGATION_DRAWER: "TOGGLE_NAVIGATION_DRAWER",
    SET_LOGGED_IN_USER: "SET_LOGGED_IN_USER",
    GET_LOGGED_IN_USER: "GET_LOGGED_IN_USER"
};

export default ActionConstants;