/*
 created by aditya on 17-02-2017
 */

"use strict";

export const TOGGLE_LOGIN_STATUS = "TOGGLE_LOGIN_STATUS";
export const GET_SELECTED_COURSE = "GET_SELECTED_COURSE";
export const UPDATE_SELECTED_COURSE = "UPDATE_SELECTED_COURSE";
export const TOGGLE_NAVIGATION_DRAWER = "TOGGLE_NAVIGATION_DRAWER";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const GET_LOGGED_IN_USER = "GET_LOGGED_IN_USER";
export const UPDATE_COURSES = "UPDATE_COURSES";
export const UPDATE_COURSE_DATA = "UPDATE_COURSE_DATA";
export const DELETE_COURSE_DATA = "DELETE_COURSE_DATA";
export const DELETE_CONTENT_WRITER_DATA = "DELETE_CONTENT_WRITER_DATA";
export const DELETE_REVIEWER_DATA = "DELETE_REVIEWER_DATA";
export const UPDATE_CONTENT_WRITER_DATA = "UPDATE_CONTENT_WRITER_DATA";
export const UPDATE_REVIEWER_DATA = "UPDATE_REVIEWER_DATA";

// source
export const INIT_SOURCES = "INIT_SOURCES";
export const DELETE_SOURCES = "DELETE_SOURCES";
export const SOURCE_IS_LOADING = "SOURCE_IS_LOADING";
export const SOURCE_HAS_ERRORED = "SOURCE_HAS_ERRORED";
export const SOURCE_REQUEST_SUCCESS = "SOURCE_REQUEST_SUCCESS";
export const SOURCE_NAME = "SOURCE_NAME";
export const SOURCE_ADD_SOURCE = "SOURCE_ADD_SOURCE";
export const SOURCE_DIALOG_STATE = "SOURCE_DIALOG_STATE";

// section
export const INIT_SECTIONS = "INIT_SECTIONS";
export const DELETE_SECTIONS = "DELETE_SECTIONS";
export const INIT_L1S = "INIT_L1S";
export const INIT_L2S = "INIT_L2S";
export const INIT_L3S = "INIT_L3S";
export const INIT_L4S = "INIT_L4S";

// theory
export const THEORY_IS_LOADING = "THEORY_IS_LOADING";
export const THEORY_UPDATE_SECTION = "THEORY_UPDATE_SECTION";
export const THEORY_UPDATE_L1 = "THEORY_UPDATE_L1";
export const THEORY_UPDATE_L2 = "THEORY_UPDATE_L2";
export const THEORY_UPDATE_L3 = "THEORY_UPDATE_L3";
export const THEORY_UPDATE_L4 = "THEORY_UPDATE_L4";
export const THEORY_UPDATE_SOURCE = "THEORY_UPDATE_SOURCE";
export const THEORY_REQUEST_SUCCESS = "THEORY_REQUEST_SUCCESS";
export const THEORY_HAS_ERRORED = "THEORY_HAS_ERRORED";
export const THEORY_UPDATE_HEADING = "THEORY_UPDATE_HEADING";
export const THEORY_UPDATE_THEORY = "THEORY_UPDATE_HEADING";
export const THEORY_UPDATE_STATUS = "QUESTION_UPDATE_STATUS";

// quesion
export const QUESTION_IS_LOADING = "QUESTION_IS_LOADING";
export const QUESTION_UPDATE_SECTION = "QUESTION_UPDATE_SECTION";
export const QUESTION_UPDATE_L1 = "QUESTION_UPDATE_L1";
export const QUESTION_UPDATE_L2 = "QUESTION_UPDATE_L2";
export const QUESTION_UPDATE_L3 = "QUESTION_UPDATE_L3";
export const QUESTION_UPDATE_L4 = "QUESTION_UPDATE_L4";
export const QUESTION_UPDATE_SOURCE = "QUESTION_UPDATE_SOURCE";
export const QUESTION_REQUEST_SUCCESS = "QUESTION_REQUEST_SUCCESS";
export const QUESTION_HAS_ERRORED = "QUESTION_HAS_ERRORED";
export const QUESTION_UPDATE_QUESTION_TYPE = "QUESTION_UPDATE_QUESTION_TYPE";
export const QUESTION_UPDATE_DIFFICULTY = "QUESTION_UPDATE_DIFFICULTY";
export const QUESTION_UPDATE_STATUS = "QUESTION_UPDATE_STATUS";