/*
 created by aditya on 17-02-2017
 */

"use strict";

export default {
    TOGGLE_LOGIN_STATUS: "TOGGLE_LOGIN_STATUS",
    GET_SELECTED_COURSE: "GET_SELECTED_COURSE",
    UPDATE_SELECTED_COURSE: "UPDATE_SELECTED_COURSE",
    TOGGLE_NAVIGATION_DRAWER: "TOGGLE_NAVIGATION_DRAWER",
    SET_LOGGED_IN_USER: "SET_LOGGED_IN_USER",
    GET_LOGGED_IN_USER: "GET_LOGGED_IN_USER",
    UPDATE_COURSES: "UPDATE_COURSES",
    UPDATE_COURSE_DATA: "UPDATE_COURSE_DATA",
    DELETE_COURSE_DATA: "DELETE_COURSE_DATA",
    DELETE_CONTENT_WRITER_DATA: "DELETE_CONTENT_WRITER_DATA",
    DELETE_REVIEWER_DATA: "DELETE_REVIEWER_DATA",
    UPDATE_CONTENT_WRITER_DATA: "UPDATE_CONTENT_WRITER_DATA",
    UPDATE_REVIEWER_DATA: "UPDATE_REVIEWER_DATA"
};
